version: "3.7"

services:
  server:
    container_name: nest-server
    restart: always
    build:
      context: ./backend-nest
      dockerfile: Dockerfile.prod
    volumes:
      - ./backend-nest:/app
    ports:
      - "5000:3000"
    links:
      - mongo
    depends_on:
      - mongo
  app:
    container_name: react-client
    build:
      context: ./react-client
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_NAME=carloserl-prod
    ports:
      - "8080:80"
    depends_on:
      - server
